spring:
    application:
        name: one_to_one_app
    datasource:
        password: Blessings@101
        url: jdbc:mysql://localhost:3306/sbms45
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
