spring:
    application:
        name: 07-api-gateway
    cloud:
        gateway:
            routes:
                - id: api-1
                  uri: lb://05-WELCOME-API
                  predicates:
                    - Path=/welcome
                - id: api-2
                  uri: lb://06-GREET-API
                  predicates:
                    - Path=/greet

server:
    port: 3333


