spring:
    application:
        name: 09-api-gateway
    cloud:
        gateway:
            routes:
                - id: api-1
                  uri: lb://WELCOME-API
                  predicates:
                      - Path=/welcome
                - id: api-2
                  uri: lb://GREET-API
                  predicates:
                      - Path=/greet

server:
    port: 3333
    
