spring:
    application:
        name: 01-circuit_breaker_app
management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
      health:
          show-details: always
    health:
      circuitbreakers:
          enabled: true
resilience4j:
    circuitbreaker:
        configs:
          default:
              register-health-indicator: true
              sliding-window-size: 10
              minimum-number-of-calls: 5
              permitted-number-of-calls-in-half-open-state: 3
              automatic-transition-from-open-to-half-open-enabled: true
              wait-duration-in-open-state:
                100s
              failure-rate-threshold: 50


